const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];

// ===== إعداد Firebase =====
firebase.initializeApp(window.firebaseConfig);
const db=firebase.firestore();
const WORKSPACE_ID=window.WORKSPACE_ID||'default';
const docRef=db.collection('workspaces').doc(WORKSPACE_ID);

const defaultStore={customers:[{id:1,name:'أحمد محمد',phone:'01012345678',note:'عميل مميز',avatar:'أ'},{id:2,name:'سارة علي',phone:'01123456789',note:'',avatar:'س'},{id:3,name:'محمد حسن',phone:'01234567890',note:'',avatar:'م'}],contracts:[{id:1,customerId:1,item:'تويوتا كورولا',total:680000,down:180000,count:10,start:'2026-08-25'},{id:2,customerId:2,item:'هيونداي إلنترا',total:540000,down:140000,count:12,start:'2026-08-28'},{id:3,customerId:3,item:'كيا سبورتاج',total:1250000,down:350000,count:18,start:'2026-09-05'}],payments:[],settings:{theme:'light'}};

let store=null, view='dashboard', filter='all', suppressSave=false;

const save=()=>{
  if(suppressSave||!store)return;
  docRef.set(store).catch(err=>{console.error(err);toast('تعذر حفظ التغييرات، تحقق من اتصال الإنترنت')});
};
const money=n=>new Intl.NumberFormat('ar-EG',{maximumFractionDigits:0}).format(n||0)+' ج.م';
const fmt=d=>new Date(d+'T12:00:00').toLocaleDateString('ar-EG',{year:'numeric',month:'short',day:'numeric'});
function installments(){let out=[];store.contracts.filter(c=>!c.archived).forEach(c=>{const remain=c.total-c.down, baseAmount=Math.round(remain/c.count), ov=c.overrides||{};for(let i=0;i<c.count;i++){let no=i+1, o=ov[no]||{}, d;if(o.due){d=new Date(o.due+'T12:00:00')}else{d=new Date(c.start+'T12:00:00');d.setMonth(d.getMonth()+i)}let amount=o.amount!=null?o.amount:baseAmount;let paid=store.payments.filter(p=>p.contractId===c.id&&p.no===no).reduce((s,p)=>s+p.amount,0);out.push({contract:c,no,amount,paid,due:d.toISOString().slice(0,10),overridden:!!(o.due||o.amount!=null)})}});return out}
function status(x){if(x.paid>=x.amount)return 'paid'; const today=new Date();today.setHours(0,0,0,0);let due=new Date(x.due+'T12:00:00');if(due<today)return 'overdue';let diff=Math.ceil((due-today)/86400000);if(diff<=7)return 'due';return x.paid>0?'partial':'notdue'}
function customer(id){return store.customers.find(x=>x.id===id)||{name:'غير معروف',avatar:'؟'}}
function monthlyCollections(){let months=[],now=new Date();for(let i=11;i>=0;i--){let d=new Date(now.getFullYear(),now.getMonth()-i,1);months.push({key:`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`,label:d.toLocaleDateString('ar-EG',{month:'short'})})}let sums=months.map(m=>({...m,total:store.payments.filter(p=>p.date&&p.date.slice(0,7)===m.key).reduce((s,p)=>s+p.amount,0)}));let max=Math.max(1,...sums.map(x=>x.total));return sums.map(x=>({...x,pct:x.total?Math.max(8,Math.round(x.total/max*100)):4}))}
function stats(){let ins=installments(), total=store.contracts.filter(c=>!c.archived).reduce((s,c)=>s+c.total,0), paid=store.payments.reduce((s,p)=>s+p.amount,0), over=ins.filter(x=>status(x)==='overdue'), today=new Date().toISOString().slice(0,10), dueToday=ins.filter(x=>x.due===today&&x.paid<x.amount);return{ins,total,paid,remain:Math.max(0,total-paid),over,dueToday}}
function setCounts(){let s=stats();$('#customerCount').textContent=store.customers.filter(c=>!c.archived).length;$('#overdueCount').textContent=s.over.length;let n=s.over.length+s.dueToday.length;['#notifCount','#topNotif'].forEach(x=>$(x).textContent=n)}
function badge(st){return `<span class="badge ${st}">${({paid:'مدفوع',partial:'دفع جزئي',overdue:'متأخر',due:'مستحق قريبًا',notdue:'لم يحن بعد'})[st]}</span>`}
function table(rows){return `<div class="card table-wrap"><table class="data-table"><thead><tr><th>العميل</th><th>رقم القسط</th><th>العقد / المنتج</th><th>القسط</th><th>الاستحقاق</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>${rows||'<tr><td colspan="7"><div class="empty">لا توجد بيانات</div></td></tr>'}</tbody></table></div>`}
function dash(){let s=stats(), recent=s.ins.filter(x=>x.paid<x.amount).sort((a,b)=>a.due.localeCompare(b.due)).slice(0,5), mc=monthlyCollections(), hasCollections=mc.some(m=>m.total>0);return `<div class="hero"><div><h2>لوحة التحكم</h2><p>إليك ملخص نشاط معرضك وأحدث المستحقات.</p></div><button class="primary" onclick="openCustomer()">+ إضافة عميل</button></div><div class="stats"><div class="stat"><div class="stat-top"><span>إجمالي المحفظة</span><div class="stat-icon purple">◈</div></div><h3>${money(s.total)}</h3><small>إجمالي قيمة العقود الحالية</small></div><div class="stat"><div class="stat-top"><span>إجمالي المحصل</span><div class="stat-icon mint">↗</div></div><h3>${money(s.paid)}</h3><small class="trend">↑ تحصيلات مسجلة</small></div><div class="stat"><div class="stat-top"><span>المبالغ المتبقية</span><div class="stat-icon amber">◷</div></div><h3>${money(s.remain)}</h3><small>المتبقي من العقود</small></div><div class="stat"><div class="stat-top"><span>الأقساط المتأخرة</span><div class="stat-icon rose">!</div></div><h3>${s.over.length}</h3><small>تحتاج إلى متابعة</small></div></div><div class="grid-2"><div class="card"><div class="card-head"><h3>أداء التحصيل الشهري</h3><span>آخر 12 شهر</span></div>${hasCollections?`<div class="chart">${mc.map(m=>`<div class="bar" style="height:${m.pct}%" data-label="${m.label}" title="${money(m.total)}"></div>`).join('')}</div>`:'<div class="empty">لا توجد تحصيلات مسجلة بعد</div>'}</div><div class="card"><div class="card-head"><h3>أقرب الاستحقاقات</h3><button class="link-btn" onclick="go('installments')">عرض الكل</button></div>${recent.slice(0,4).map(x=>`<div class="upcoming"><div class="calendar-dot">${x.no}</div><div><b>${customer(x.contract.customerId).name}</b><small>${x.contract.item} · ${fmt(x.due)}</small></div><div class="amount">${money(x.amount-x.paid)}</div></div>`).join('')||'<div class="empty">لا توجد استحقاقات</div>'}</div></div><div style="height:18px"></div><div class="card"><div class="card-head"><h3>آخر الأقساط</h3><button class="link-btn" onclick="go('installments')">إدارة الأقساط</button></div>${table(recent.map(x=>installmentRow(x)).join(''))}</div>`}
function installmentRow(x){let c=customer(x.contract.customerId),st=status(x);return `<tr><td><div class="customer-cell"><div class="mini-avatar">${c.avatar||c.name[0]}</div><div><b>${c.name}</b><br><small>${c.phone}</small></div></div></td><td><span class="tag">قسط ${x.no} / ${x.contract.count}</span></td><td>${x.contract.item}</td><td><b>${money(x.amount-x.paid)}</b>${x.paid?`<br><small>تم دفع ${money(x.paid)}</small>`:''}</td><td>${fmt(x.due)}${x.overridden?' <small class="tag">معدّل</small>':''}</td><td>${badge(st)}</td><td><div class="row-actions"><button class="link-btn" onclick="openPayment(${x.contract.id},${x.no})">تسجيل دفعة</button><button class="link-btn" onclick="editInstallment(${x.contract.id},${x.no})">تعديل</button></div></td></tr>`}
function customers(){return `<div class="hero"><div><h2>العملاء</h2><p>إدارة بيانات العملاء والعقود المرتبطة بهم.</p></div><button class="primary" onclick="openCustomer()">+ إضافة عميل</button></div><div class="section-toolbar"><input class="search" placeholder="ابحث بالاسم أو رقم الهاتف..." oninput="searchCustomers(this.value)"></div><div class="card table-wrap"><table class="data-table"><thead><tr><th>العميل</th><th>رقم الهاتف</th><th>عدد العقود</th><th>إجمالي المتبقي</th><th></th></tr></thead><tbody id="customersBody">${customerRows(store.customers.filter(c=>!c.archived))}</tbody></table></div>`}
function customerRows(list){return list.map(c=>{let cs=store.contracts.filter(x=>x.customerId===c.id&&!x.archived), remain=cs.reduce((s,x)=>s+(x.total-x.down),0)-store.payments.filter(p=>cs.some(x=>x.id===p.contractId)).reduce((s,p)=>s+p.amount,0);return `<tr><td><div class="customer-cell"><div class="mini-avatar">${c.avatar||c.name[0]}</div><div><b>${c.name}</b><br><small>${c.note||'عميل مسجل'}</small></div></div></td><td>${c.phone}</td><td>${cs.length} عقد</td><td>${money(Math.max(0,remain))}</td><td><div class="row-actions"><button class="link-btn" onclick="customerDetails(${c.id})">عرض الملف</button><button class="link-btn" onclick="editCustomer(${c.id})">تعديل</button><button class="link-btn danger" onclick="confirmDeleteCustomer(${c.id})">حذف</button></div></td></tr>`}).join('')||'<tr><td colspan="5"><div class="empty">لا يوجد عملاء حتى الآن</div></td></tr>'}
function contracts(){return `<div class="hero"><div><h2>العقود</h2><p>إنشاء وإدارة عقود البيع والتقسيط.</p></div><button class="primary" onclick="openContract()">+ عقد جديد</button></div><div class="card table-wrap"><table class="data-table"><thead><tr><th>العميل</th><th>المنتج</th><th>إجمالي السعر</th><th>المقدم</th><th>عدد الأقساط</th><th>بداية العقد</th><th></th></tr></thead><tbody>${store.contracts.filter(c=>!c.archived).map(c=>`<tr><td>${customer(c.customerId).name}</td><td><b>${c.item}</b></td><td>${money(c.total)}</td><td>${money(c.down)}</td><td>${c.count}</td><td>${fmt(c.start)}</td><td><div class="row-actions"><button class="link-btn" onclick="editContract(${c.id})">تعديل</button><button class="link-btn danger" onclick="confirmDeleteContract(${c.id})">حذف</button></div></td></tr>`).join('')||'<tr><td colspan="7"><div class="empty">لا توجد عقود</div></td></tr>'}</tbody></table></div>`}
function installmentsView(){let list=stats().ins.filter(x=>filter==='all'||status(x)===filter);return `<div class="hero"><div><h2>الأقساط</h2><p>تابع كل الاستحقاقات وسجل الدفعات من مكان واحد.</p></div><button class="primary" onclick="openContract()">+ عقد جديد</button></div><div class="filter-tabs">${[['all','الكل'],['due','قريبًا'],['overdue','متأخر'],['paid','مدفوع'],['partial','دفع جزئي'],['notdue','لم يحن بعد']].map(x=>`<button class="${filter===x[0]?'active':''}" onclick="filterInstallments('${x[0]}')">${x[1]}</button>`).join('')}</div><div style="height:15px"></div>${table(list.sort((a,b)=>a.due.localeCompare(b.due)).map(installmentRow).join(''))}`}
function payments(){let p=[...store.payments].reverse();return `<div class="hero"><div><h2>المدفوعات</h2><p>سجل كامل بجميع الدفعات التي تم تحصيلها.</p></div></div><div class="card">${p.map(x=>{let c=store.contracts.find(q=>q.id===x.contractId);if(!c)return'';let cu=customer(c.customerId);return `<div class="payment-card"><div class="calendar-dot">✓</div><div><b>${cu.name}</b><small>${c.item} · القسط رقم ${x.no}</small></div><div class="money">${money(x.amount)}<br><small>${fmt(x.date)}</small></div><div class="row-actions"><button class="link-btn" onclick="editPayment(${x.id})">تعديل</button><button class="link-btn danger" onclick="confirmDeletePayment(${x.id})">حذف</button></div></div>`}).join('')||'<div class="empty"><strong>لا توجد دفعات بعد</strong>سجل أول دفعة من صفحة الأقساط</div>'}</div>`}
function calendar(){let now=new Date(), y=now.getFullYear(),m=now.getMonth(), first=new Date(y,m,1).getDay(), days=new Date(y,m+1,0).getDate(), ev=stats().ins.filter(x=>x.due.slice(0,7)===`${y}-${String(m+1).padStart(2,'0')}`);let cells=[];for(let i=0;i<(first+1)%7;i++)cells.push('<div></div>');for(let d=1;d<=days;d++){let ds=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`, es=ev.filter(x=>x.due===ds);cells.push(`<div class="day"><span class="n">${d}</span>${es.slice(0,2).map(x=>`<div class="event ${status(x)==='overdue'?'red':''}">${customer(x.contract.customerId).name} · ${money(x.amount-x.paid)}</div>`).join('')}</div>`)}return `<div class="hero"><div><h2>تقويم الاستحقاقات</h2><p>شهر ${now.toLocaleDateString('ar-EG',{month:'long',year:'numeric'})}</p></div><button class="primary" onclick="go('installments')">إدارة الأقساط</button></div><div class="card"><div class="calendar-grid">${['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'].map(x=>`<div class="day-name">${x}</div>`).join('')}${cells.join('')}</div></div>`}
function reports(){let s=stats();return `<div class="hero"><div><h2>التقارير والتحليلات</h2><p>مؤشرات مالية تساعدك على اتخاذ قرارات أفضل.</p></div><button class="secondary" onclick="toast('تم تجهيز التقرير للطباعة')">تصدير التقرير</button></div><div class="report-grid"><div class="metric"><span>نسبة التحصيل</span><b>${s.total?Math.round(s.paid/s.total*100):0}%</b></div><div class="metric"><span>إجمالي التحصيلات</span><b>${money(s.paid)}</b></div><div class="metric"><span>المبالغ المتأخرة</span><b>${money(s.over.reduce((a,x)=>a+x.amount-x.paid,0))}</b></div></div><div style="height:18px"></div><div class="grid-2"><div class="card"><div class="card-head"><h3>توزيع حالة الأقساط</h3></div><div class="chart">${['paid','partial','due','overdue'].map((st,i)=>{let n=s.ins.filter(x=>status(x)===st).length;return `<div class="bar" style="height:${Math.max(12,Math.min(100,n*18))}%" data-label="${['مدفوع','جزئي','قريب','متأخر'][i]}"></div>`}).join('')}</div></div><div class="card"><div class="card-head"><h3>ملخص الأداء</h3></div><div class="upcoming"><div class="calendar-dot">👥</div><div><b>${store.customers.filter(c=>!c.archived).length} عميل</b><small>عملاء مسجلون بالنظام</small></div></div><div class="upcoming"><div class="calendar-dot">📄</div><div><b>${store.contracts.filter(c=>!c.archived).length} عقد</b><small>عقود نشطة</small></div></div><div class="upcoming"><div class="calendar-dot">⚠</div><div><b>${s.over.length} قسط متأخر</b><small>يحتاج متابعة عاجلة</small></div></div></div></div>`}
function notifications(){let s=stats(), list=[...s.over,...s.dueToday];return `<div class="hero"><div><h2>التنبيهات</h2><p>إشعارات الاستحقاقات والمتابعات المهمة.</p></div><button class="secondary" onclick="toast('تم تحديد جميع التنبيهات كمقروءة')">تحديد كمقروء</button></div><div class="card">${list.map(x=>`<div class="payment-card"><div class="calendar-dot">${status(x)==='overdue'?'!':'🔔'}</div><div><b>${status(x)==='overdue'?'قسط متأخر':'قسط مستحق اليوم'} — ${customer(x.contract.customerId).name}</b><small>${x.contract.item} · القسط رقم ${x.no} · ${money(x.amount-x.paid)}</small></div><button class="link-btn" onclick="openPayment(${x.contract.id},${x.no})">فتح</button></div>`).join('')||'<div class="empty"><strong>كل شيء على ما يرام 🎉</strong>لا توجد تنبيهات مهمة حاليًا</div>'}</div>`}
function settings(){return `<div class="hero"><div><h2>الإعدادات</h2><p>خصص النظام بالطريقة المناسبة لعملك.</p></div></div><div class="card"><div class="settings-row"><div><b>الوضع الداكن</b><br><small>تغيير مظهر لوحة التحكم</small></div><div class="switch ${document.body.classList.contains('dark')?'on':''}" onclick="toggleTheme(this)"></div></div><div class="settings-row"><div><b>تذكير قبل الاستحقاق</b><br><small>إظهار التنبيهات قبل 7 أيام</small></div><div class="switch on"></div></div><div class="settings-row"><div><b>نسخ احتياطي محلي</b><br><small>تصدير البيانات إلى ملف JSON</small></div><button class="secondary" onclick="exportData()">تصدير البيانات</button></div></div>`}
function render(){let pages={dashboard:dash,customers,contracts,installments:installmentsView,payments,calendar,reports,notifications,settings};$('#content').innerHTML=pages[view]();let titles={dashboard:['لوحة التحكم','نظرة عامة على أداء أعمالك اليوم'],customers:['العملاء','إدارة قاعدة بيانات العملاء'],contracts:['العقود','إدارة عقود البيع والتقسيط'],installments:['الأقساط','متابعة الاستحقاقات والمدفوعات'],payments:['المدفوعات','سجل التحصيلات'],calendar:['التقويم','عرض مواعيد الاستحقاق'],reports:['التقارير','تحليلات مالية وتشغيلية'],notifications:['التنبيهات','آخر التحديثات والاستحقاقات'],settings:['الإعدادات','تخصيص النظام']};$('#pageTitle').textContent=titles[view][0];$('#pageSubtitle').textContent=titles[view][1];$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));setCounts();save()}
function go(v){view=v;render();if(innerWidth<1050)$('#sidebar').classList.remove('open')}
function searchCustomers(q){$('#customersBody').innerHTML=customerRows(store.customers.filter(c=>!c.archived&&(c.name+c.phone).includes(q)))}function filterInstallments(f){filter=f;render()}
function openModal(html){$('#modalContent').innerHTML=html;$('#modal').classList.remove('hidden')}function closeModal(){$('#modal').classList.add('hidden')}
function openCustomer(){openModal(`<h2>إضافة عميل جديد</h2><p>أدخل بيانات العميل الأساسية للبدء.</p><form onsubmit="saveCustomer(event)"><div class="form-grid"><div class="field"><label>اسم العميل *</label><input name="name" required placeholder="مثال: أحمد محمد"></div><div class="field"><label>رقم الهاتف *</label><input name="phone" required placeholder="01xxxxxxxxx"></div><div class="field full"><label>ملاحظات</label><textarea name="note" rows="3" placeholder="أي ملاحظات إضافية..."></textarea></div></div><div class="form-actions"><button type="button" class="ghost" onclick="closeModal()">إلغاء</button><button class="primary">حفظ العميل</button></div></form>`)}
function saveCustomer(e){e.preventDefault();let f=new FormData(e.target);store.customers.push({id:Date.now(),name:f.get('name'),phone:f.get('phone'),note:f.get('note'),avatar:f.get('name')[0]});save();closeModal();toast('تمت إضافة العميل بنجاح');render()}
function esc(s){return (s||'').replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;')}
function editCustomer(id){let c=customer(id);if(!c||c.id===undefined)return toast('تعذر العثور على العميل');openModal(`<h2>تعديل بيانات العميل</h2><p>عدّل بيانات العميل ثم احفظ التغييرات.</p><form onsubmit="saveEditCustomer(event,${id})"><div class="form-grid"><div class="field"><label>اسم العميل *</label><input name="name" required value="${esc(c.name)}"></div><div class="field"><label>رقم الهاتف *</label><input name="phone" required value="${esc(c.phone)}"></div><div class="field full"><label>ملاحظات</label><textarea name="note" rows="3">${esc(c.note)}</textarea></div></div><div class="form-actions"><button type="button" class="ghost" onclick="closeModal()">إلغاء</button><button class="primary">حفظ التعديلات</button></div></form>`)}
function saveEditCustomer(e,id){e.preventDefault();let f=new FormData(e.target),c=store.customers.find(x=>x.id===id);if(!c)return;c.name=f.get('name');c.phone=f.get('phone');c.note=f.get('note');c.avatar=f.get('name')[0];save();closeModal();toast('تم تحديث بيانات العميل بنجاح');render()}
let _confirmCb=null;
function confirmDialog(title,msg,cb){_confirmCb=cb;openModal(`<h2>${title}</h2><p>${msg}</p><div class="form-actions"><button type="button" class="ghost" onclick="closeModal()">إلغاء</button><button class="danger" onclick="_runConfirm()">تأكيد الحذف</button></div>`)}
function _runConfirm(){let cb=_confirmCb;_confirmCb=null;closeModal();if(cb)cb()}
function confirmDeleteCustomer(id){let c=customer(id), n=store.contracts.filter(x=>x.customerId===id&&!x.archived).length;confirmDialog('حذف العميل',`هل أنت متأكد من حذف "${esc(c.name)}"؟ ${n?`سيتم أيضًا إخفاء ${n} عقد مرتبط به. `:''}العميل والبيانات هيتشالوا من القائمة بس هيفضلوا محفوظين، ومش هتقدر تسترجعهم من الواجهة.`,()=>deleteCustomer(id))}
function deleteCustomer(id){let c=store.customers.find(x=>x.id===id);if(!c)return;c.archived=true;store.contracts.filter(x=>x.customerId===id).forEach(x=>x.archived=true);save();toast('تم حذف العميل');view='customers';render()}
function openContract(){let active=store.customers.filter(c=>!c.archived);if(!active.length)return toast('أضف عميلًا أولًا');openModal(`<h2>إنشاء عقد تقسيط</h2><p>سيتم إنشاء جدول الأقساط تلقائيًا.</p><form onsubmit="saveContract(event)"><div class="form-grid"><div class="field"><label>العميل *</label><select name="customerId" required>${active.map(c=>`<option value="${c.id}">${c.name}</option>`).join('')}</select></div><div class="field"><label>المنتج / السيارة *</label><input name="item" required placeholder="مثال: تويوتا كورولا"></div><div class="field"><label>السعر الإجمالي *</label><input name="total" type="number" min="1" required></div><div class="field"><label>المقدم *</label><input name="down" type="number" min="0" value="0" required></div><div class="field"><label>عدد الأقساط *</label><input name="count" type="number" min="1" value="12" required></div><div class="field"><label>تاريخ أول قسط *</label><input name="start" type="date" value="${new Date().toISOString().slice(0,10)}" required></div></div><div class="form-actions"><button type="button" class="ghost" onclick="closeModal()">إلغاء</button><button class="primary">إنشاء العقد</button></div></form>`)}
function saveContract(e){e.preventDefault();let f=new FormData(e.target),c={id:Date.now(),customerId:+f.get('customerId'),item:f.get('item'),total:+f.get('total'),down:+f.get('down'),count:+f.get('count'),start:f.get('start')};if(c.down>=c.total)return toast('المقدم يجب أن يكون أقل من إجمالي السعر');store.contracts.push(c);save();closeModal();toast('تم إنشاء العقد وجدول الأقساط تلقائيًا');view='installments';render()}
function editContract(id){let c=store.contracts.find(x=>x.id===id);if(!c)return;let opts=store.customers.filter(x=>!x.archived||x.id===c.customerId);openModal(`<h2>تعديل العقد</h2><p>تنبيه: تغيير المبالغ أو عدد الأقساط سيعيد حساب جدول الأقساط وأي تعديلات مخصّصة عليه.</p><form onsubmit="saveEditContract(event,${id})"><div class="form-grid"><div class="field"><label>العميل *</label><select name="customerId" required>${opts.map(x=>`<option value="${x.id}" ${x.id===c.customerId?'selected':''}>${x.name}</option>`).join('')}</select></div><div class="field"><label>المنتج / السيارة *</label><input name="item" required value="${esc(c.item)}"></div><div class="field"><label>السعر الإجمالي *</label><input name="total" type="number" min="1" required value="${c.total}"></div><div class="field"><label>المقدم *</label><input name="down" type="number" min="0" required value="${c.down}"></div><div class="field"><label>عدد الأقساط *</label><input name="count" type="number" min="1" required value="${c.count}"></div><div class="field"><label>تاريخ أول قسط *</label><input name="start" type="date" required value="${c.start}"></div></div><div class="form-actions"><button type="button" class="ghost" onclick="closeModal()">إلغاء</button><button class="primary">حفظ التعديلات</button></div></form>`)}
function saveEditContract(e,id){e.preventDefault();let f=new FormData(e.target),c=store.contracts.find(x=>x.id===id);if(!c)return;let total=+f.get('total'),down=+f.get('down'),count=+f.get('count');if(down>=total)return toast('المقدم يجب أن يكون أقل من إجمالي السعر');c.customerId=+f.get('customerId');c.item=f.get('item');c.total=total;c.down=down;c.count=count;c.start=f.get('start');c.overrides={};save();closeModal();toast('تم تحديث العقد بنجاح');render()}
function confirmDeleteContract(id){let c=store.contracts.find(x=>x.id===id);if(!c)return;confirmDialog('حذف العقد',`هل أنت متأكد من حذف عقد "${esc(c.item)}"؟ سيختفي من القوائم لكن هيفضل محفوظ في قاعدة البيانات.`,()=>deleteContract(id))}
function deleteContract(id){let c=store.contracts.find(x=>x.id===id);if(!c)return;c.archived=true;save();toast('تم حذف العقد');render()}
function openPayment(contractId,no){let x=installments().find(i=>i.contract.id===contractId&&i.no===no);if(!x)return;openModal(`<h2>تسجيل دفعة</h2><p>${customer(x.contract.customerId).name} · ${x.contract.item}</p><div class="card" style="box-shadow:none;background:#f7f8fc"><b>القسط رقم ${no}</b><div style="margin-top:8px">المطلوب: <b>${money(x.amount)}</b> — المدفوع: <b>${money(x.paid)}</b></div></div><form onsubmit="savePayment(event,${contractId},${no},${x.amount-x.paid})"><div class="form-grid"><div class="field"><label>قيمة الدفعة *</label><input name="amount" type="number" min="1" max="${x.amount-x.paid}" value="${x.amount-x.paid}" required></div><div class="field"><label>تاريخ الدفع</label><input name="date" type="date" value="${new Date().toISOString().slice(0,10)}" required></div></div><div class="form-actions"><button type="button" class="ghost" onclick="closeModal()">إلغاء</button><button class="primary">تأكيد الدفعة</button></div></form>`)}
function savePayment(e,contractId,no,max){e.preventDefault();let f=new FormData(e.target),a=+f.get('amount');if(a>max)return toast('قيمة الدفعة أكبر من المبلغ المتبقي');store.payments.push({id:Date.now(),contractId,no,amount:a,date:f.get('date')});save();closeModal();toast('تم تسجيل الدفعة بنجاح ✓');render()}
function editInstallment(contractId,no){let x=installments().find(i=>i.contract.id===contractId&&i.no===no);if(!x)return;openModal(`<h2>تعديل القسط رقم ${no}</h2><p>${customer(x.contract.customerId).name} · ${x.contract.item}</p><form onsubmit="saveInstallmentEdit(event,${contractId},${no})"><div class="form-grid"><div class="field"><label>تاريخ الاستحقاق *</label><input name="due" type="date" required value="${x.due}"></div><div class="field"><label>قيمة القسط *</label><input name="amount" type="number" min="${x.paid||1}" required value="${x.amount}"></div></div><div class="form-actions">${x.overridden?`<button type="button" class="ghost" onclick="resetInstallment(${contractId},${no})">استعادة الافتراضي</button>`:''}<button type="button" class="ghost" onclick="closeModal()">إلغاء</button><button class="primary">حفظ</button></div></form>`)}
function saveInstallmentEdit(e,contractId,no){e.preventDefault();let f=new FormData(e.target),due=f.get('due'),amount=+f.get('amount'),c=store.contracts.find(x=>x.id===contractId);if(!c)return;let x=installments().find(i=>i.contract.id===contractId&&i.no===no);if(amount<x.paid)return toast('القيمة أقل من المبلغ المدفوع بالفعل لهذا القسط');if(!c.overrides)c.overrides={};c.overrides[no]={due,amount};save();closeModal();toast('تم تحديث بيانات القسط');render()}
function resetInstallment(contractId,no){let c=store.contracts.find(x=>x.id===contractId);if(c&&c.overrides)delete c.overrides[no];save();closeModal();toast('تم استعادة القيم الافتراضية');render()}
function editPayment(id){let p=store.payments.find(x=>x.id===id);if(!p)return;let c=store.contracts.find(x=>x.id===p.contractId);if(!c)return;openModal(`<h2>تعديل الدفعة</h2><p>${customer(c.customerId).name} · ${c.item} · القسط رقم ${p.no}</p><form onsubmit="savePaymentEdit(event,${id})"><div class="form-grid"><div class="field"><label>قيمة الدفعة *</label><input name="amount" type="number" min="1" required value="${p.amount}"></div><div class="field"><label>تاريخ الدفع *</label><input name="date" type="date" required value="${p.date}"></div></div><div class="form-actions"><button type="button" class="ghost" onclick="closeModal()">إلغاء</button><button class="primary">حفظ</button></div></form>`)}
function savePaymentEdit(e,id){e.preventDefault();let f=new FormData(e.target),p=store.payments.find(x=>x.id===id);if(!p)return;p.amount=+f.get('amount');p.date=f.get('date');save();closeModal();toast('تم تحديث الدفعة بنجاح');render()}
function confirmDeletePayment(id){confirmDialog('حذف الدفعة','هل أنت متأكد من حذف هذه الدفعة؟ سيصبح القسط المرتبط بها غير مدفوع بهذا المقدار.',()=>deletePayment(id))}
function deletePayment(id){store.payments=store.payments.filter(x=>x.id!==id);save();toast('تم حذف الدفعة');render()}
function customerDetails(id){let c=customer(id), cs=store.contracts.filter(x=>x.customerId===id&&!x.archived), paid=store.payments.filter(p=>cs.some(x=>x.id===p.contractId)).reduce((s,p)=>s+p.amount,0), total=cs.reduce((s,x)=>s+x.total-x.down,0), pct=total?Math.min(100,Math.round(paid/total*100)):0;openModal(`<div style="display:flex;justify-content:space-between;align-items:flex-start;gap:12px"><div><h2>${c.name}</h2><p>${c.phone} ${c.note?'· '+c.note:''}</p></div><div class="row-actions" style="margin-inline-end:34px"><button class="secondary" onclick="editCustomer(${id})">تعديل البيانات</button><button class="ghost danger" onclick="confirmDeleteCustomer(${id})">حذف</button></div></div><div class="card" style="box-shadow:none"><div class="stats" style="grid-template-columns:repeat(3,1fr);margin:0"><div class="stat"><span>إجمالي التقسيط</span><h3>${money(total)}</h3></div><div class="stat"><span>المدفوع</span><h3>${money(paid)}</h3></div><div class="stat"><span>نسبة السداد</span><h3>${pct}%</h3></div></div><div style="margin-top:15px" class="progress"><span style="width:${pct}%"></span></div></div><div class="card" style="box-shadow:none;margin-top:14px"><b>العقود</b>${cs.map(x=>`<div class="upcoming"><div class="calendar-dot">📄</div><div><b>${x.item}</b><small>${x.count} أقساط · البداية ${fmt(x.start)}</small></div><div class="amount">${money(x.total-x.down)}</div></div>`).join('')||'<div class="empty">لا توجد عقود لهذا العميل</div>'}</div>`)}
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>e.classList.remove('show'),2600)}function toggleTheme(el){document.body.classList.toggle('dark');store.settings.theme=document.body.classList.contains('dark')?'dark':'light';save();el?.classList.toggle('on')}
function exportData(){let blob=new Blob([JSON.stringify(store,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='qest-backup.json';a.click();URL.revokeObjectURL(a.href);toast('تم تصدير نسخة احتياطية')}
window.openCustomer=openCustomer;window.saveCustomer=saveCustomer;window.editCustomer=editCustomer;window.saveEditCustomer=saveEditCustomer;window.confirmDeleteCustomer=confirmDeleteCustomer;window.deleteCustomer=deleteCustomer;window._runConfirm=_runConfirm;window.openContract=openContract;window.saveContract=saveContract;window.editContract=editContract;window.saveEditContract=saveEditContract;window.confirmDeleteContract=confirmDeleteContract;window.deleteContract=deleteContract;window.openPayment=openPayment;window.savePayment=savePayment;window.editInstallment=editInstallment;window.saveInstallmentEdit=saveInstallmentEdit;window.resetInstallment=resetInstallment;window.editPayment=editPayment;window.savePaymentEdit=savePaymentEdit;window.confirmDeletePayment=confirmDeletePayment;window.deletePayment=deletePayment;window.closeModal=closeModal;window.customerDetails=customerDetails;window.searchCustomers=searchCustomers;window.filterInstallments=filterInstallments;window.go=go;window.toast=toast;window.toggleTheme=toggleTheme;window.exportData=exportData;
// ===== مزامنة البيانات مع Firestore =====
function startSync(){
  docRef.onSnapshot(async snap=>{
    if(!snap.exists){await docRef.set(defaultStore);return}
    suppressSave=true;
    store=snap.data();
    document.body.classList.toggle('dark',store.settings?.theme==='dark');
    render();
    suppressSave=false;
  },err=>{console.error(err);toast('تعذر الاتصال بقاعدة البيانات')});
}
startSync();

// ===== ربط عناصر الواجهة الثابتة =====
$$('.nav-item,.notif').forEach(b=>b.addEventListener('click',()=>go(b.dataset.view)));$('#settingsBtn').addEventListener('click',()=>go('settings'));$('#themeBtn').addEventListener('click',()=>toggleTheme());$('#menuBtn').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));$('.modal-close').addEventListener('click',closeModal);$('.modal-backdrop').addEventListener('click',closeModal);$('#today').textContent=new Date().toLocaleDateString('ar-EG',{weekday:'long',day:'numeric',month:'long'});
